project:
  type: website
  output-dir: _site
  pre-render: pre_render.py
  post-render: post_render.py
  resources: 
    - api/**
  render:
    - "*.qmd"
    - "notebooks/*.ipynb"
    # - "!ignored-dir/"
    # - "!ignored-file.qmd"
    # they should go after things we do want to render


website:
  title: "Bambi"
  description: "BAyesian Model Building Interface in Python"
  repo-url: https://github.com/bambinos/bambi
  page-navigation: true
  favicon: "logos/favicon.png"
  page-footer:
    center: Â© Copyright 2024, The developers of Bambi.
  navbar:
    title: false
    background: light
    search: true
    pinned: true
    logo: "logos/RGB/Bambi_logo.png"
    logo-alt: "bambi-home"
    right:
      - text: Getting Started
        href: notebooks/getting_started.ipynb
      - text: API Reference
        href: api/index.html
      - text: Examples
        href: notebooks/index.qmd
      - text: FAQ
        file: faq.qmd
      - text: Changelog
        file: changelog.qmd
      - text: Contact
        file: contact.qmd
      - icon: github
        href: https://github.com/bambinos/bambi

  sidebar:
    - id: reference
      contents: _sidebar.yml
    - id: examples
      style: floating
      collapse-level: 1
      contents:
        - notebooks/index.qmd
        - section: Linear regression models
          contents:
            - notebooks/t-test.ipynb
            - notebooks/ESCS_multiple_regression.ipynb
            - notebooks/splines_cherry_blossoms.ipynb
            - notebooks/multi-level_regression.ipynb
            - notebooks/sleepstudy.ipynb
            - notebooks/radon_example.ipynb
            - notebooks/Strack_RRR_re_analysis.ipynb
            - notebooks/shooter_crossed_random_ANOVA.ipynb
            - notebooks/t_regression.ipynb
            - notebooks/predict_new_groups.ipynb
            - notebooks/polynomial_regression.ipynb
        - section: Generalized linear models
          contents:
              - notebooks/logistic_regression.ipynb
              - notebooks/model_comparison.ipynb
              - notebooks/hierarchical_binomial_bambi.ipynb
              - notebooks/alternative_links_binary.ipynb
              - notebooks/wald_gamma_glm.ipynb
              - notebooks/negative_binomial.ipynb
              - notebooks/beta_regression.ipynb
              - notebooks/categorical_regression.ipynb
              - notebooks/circular_regression.ipynb
              - notebooks/quantile_regression.ipynb
              - notebooks/mister_p.ipynb
              - notebooks/ordinal_regression.ipynb
              - notebooks/zero_inflated_regression.ipynb
        - section: More advanced models
          contents:
            - notebooks/distributional_models.ipynb
            - notebooks/hsgp_1d.ipynb
            - notebooks/hsgp_2d.ipynb
            - notebooks/survival_model.ipynb
            - notebooks/orthogonal_polynomial_reg.ipynb
        - section: Tools to interpret model outputs
          contents:
              - notebooks/plot_predictions.ipynb
              - notebooks/plot_comparisons.ipynb
              - notebooks/plot_slopes.ipynb
              - notebooks/interpret_advanced_usage.ipynb
        - section: Alternative sampling backends
          contents:
              - notebooks/alternative_samplers.ipynb

quartodoc:
  style: pkgdown
  dir: api
  package: bambi # the name used to import the package
  sidebar: api/_sidebar.yml # write sidebar data to this file
  sections:
    - title: Model
      desc: The basics
      contents:
        - Model
        - Formula
    - title: Setting up priors
      desc: ""
      contents:
        - Prior
    - title: Custom families
      desc: ""
      contents:
        - Family
        - Likelihood
        - Link
    - title: Plots
      desc: ""
      contents:
        - interpret.plot_comparisons
        - interpret.plot_predictions
        - interpret.plot_slopes
    - title: Interpretations
      desc: ""
      contents:
        - interpret.comparisons
        - interpret.predictions
        - interpret.slopes
    - title: Data
      desc: ""
      contents:
        - clear_data_home
        - load_data
 

# Tell quarto to read the generated sidebar
metadata-files:
  - api/_sidebar.yml

# filters:
#   - interlinks

# interlinks:
#   sources: {}

# profile:
#   default: latest

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


# https://github.com/quarto-dev/quarto-web/tree/main/docs/gallery
