name: Build and publish documentation

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build-docs:
    if: github.repository == 'bambinos/bambi'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.7.32 # since this is my local version, we could change it

      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.48.0
          environments: "dev"

      - name: Build documentation
        shell: bash
        # 1. I have to 'cd' because interlinks does not allow to pass a different path
        # 2. sphobjinv and mv are needed to offer objects.inv to other projects
        run: |
          cd docs
          pixi run -e dev python -m quartodoc build --verbose
          pixi run -e dev python -m quartodoc interlinks
          quarto render
          touch _site/.nojekyll
          pixi run -e dev python -m sphobjinv convert -o zlib objects.txt objects.inv
          mv objects.inv _site/objects.inv
          ls _site

      - name: Publish documentation to GitHub
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
          path: docs/_site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


# NOTES
# 1. The job runs only in the bambinos/bambi repository. It does not make sense to do it elsewhere.
# 2. The rendered webpage is published ONLY when the job was triggered by:
#   - A commit to main
#   - A tagged release
