name: Rebuilt entire documentation

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - name: Install Bambi and all its dependencies
        run: |
          conda install -c conda-forge python-graphviz
          conda install pip
          pip install .
          pip install bambi[dev]
          pip install bambi[jax]

      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: docs/_build/html

      - name: Remove and build documentation from scratch
        run: |
          rm -rd docs/_build/html
          sphinx-build docs docs/_build/html
          touch docs/_build/html/.nojekyll

      - name: Publish docs to gh-pages
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501 # v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          keep_files: true
